"use client";

import Link from "next/link";
import { useParams } from "next/navigation";

export default function ZonePage() {
  const params = useParams();
  const zone = params?.city;
  console.log("hjdcg =>",zone)

  const zones = {
    "central-delhi": ['Ajmeri Gate',
      'Amrita Shergill Marg',
      'Arya Nagar',
      'Asaf Ali Road',
      'Ashoka Road',
      'Bara Hindu Rao',
      'Barakhamba',
      'Barakhamba Road',
      'Beadon Pura',
      'Bengali Market',
      'Bhagirath Palace',
      'Block 13 WEA',
      'Block 14 WEA',
      'Block 16 WEA',
      'Block 16A WEA',
      'Block 22B Dev Nagar',
      'Block 29 Regar Pura',
      'Block 44Q Beadon Pura',
      'Block 6 WEA',
      'Block 6A WEA',
      'Block 8 WEA',
      'Block 8A WEA',
      'Block B New Rajinder Nagar',
      'Block E Jhandewalan Extension',
      'Channa Market',
      'Chawri Bazar',
      'Chhippy Wada',
      'Chuna Mandi',
      'Connaught Place',
      'Daryaganj',
      'Deputy Ganj',
      'Dev Nagar',
      'Diz Area',
      'Hauz Qazi',
      'IP Estate',
      'India Gate',
      'Ito',
      'Jama Masjid',
      'Kaka Nagar',
      'Kalan Mahal',
      'Kamla Market',
      'Khari Baoli',
      'Kishan Ganj',
      'Krishna Nagar',
      'Malcha',
      'Mandi House',
      'Multani Dhanda',
      'Naya Bazar',
      'New Rajendra Nagar',
      'Nizamuddin West',
      'Old Rajinder Nagar',
      'Padam Nagar',
      'Pahari Dhiraj',
      'Pragati Maidan',
      'Prasad Nagar',
      'Press Enclave',
      'Prithviraj Road',
      'Pusa Road',
      'Raisina Hills',
      'Rajender Nagar',
      'Rajendra Park',
      'Rajinder Nagar',
      'Rajiv Chowk',
      'Regar Pura',
      'Sant Nagar',
      'Sarai Rohilla',
      'Shaheed Bhagat Singh Marg',
      'Sita Ram Bazar',
      'Sunder Nagar',
      'Swami Dayanand Colony',
      'Teliwara',
      'Tilak Marg',
      'Turkman Gate',
      'Vikram Nagar'],


    "north-delhi": [  'Adarsh Nagar',
      'Adarsh Nagar Extension',
      'Ajit Vihar',
      'Alipur',
      'Amrit Vihar',
      'Anand Vihar',
      'Ashok Vihar',
      'Ashok Vihar Phase 1',
      'Ashok Vihar Phase 2',
      'Ashok Vihar Phase 3',
      'Ashok Vihar Phase 4',
      'Avantika Pocket E Vijay Vihar Phase 2',
      'Avantika Sector 1',
      'Azad Market',
      'Azadpur',
      'B Block Baba Colony',
      'B Block Kaushik Enclave',
      'B Block Prashant Vihar',
      'B Block Shastri Nagar',
      'B Block Virendar Nagar',
      'B Block West Sant Nagar',
      'BM Block West Shalimar Bagh',
      'Baba Colony',
      'Badli',
      'Badli Industrial Area',
      'Bakhtawarpur',
      'Banarsi Das Estate',
      'Bankner Village',
      'Bawana',
      'Begam Pur',
      'Begam Vihar',
      'Begampur',
      'Begampur Extension',
      'Bengali Colony',
      'Bhai Parmanand Colony',
      'Bhalswa',
      'Bhalswa Dairy',
      'Bharat Nagar',
      'Bhorgarh',
      'Block A West Sant Nagar',
      'Block B Pocket C Sector 1 Rohini',
      'Block B, Sector 17, Rohini',
      'Block C Vijay Vihar Phase 1',
      'Block D Shastri Nagar',
      'Block E Saraswati Vihar',
      'Block E Shastri Nagar',
      'Block E2 Shastri Nagar',
      'Block F-1U Uttari Pitampura',
      'Block Fu Uttari Pitampura',
      'Block G, Sector 16 Rohini',
      'Block L Shastri Nagar',
      'Budh Vihar',
      'Budh Vihar Phase 1',
      'Budh Vihar Phase 2',
      'Budhh Vihar Market',
      'Budhpur',
      'Burari',
      'Burari Garhi',
      'C6 Keshav Puram',
      'CC Colony',
      'Chandan Vihar',
      'Civil Lines',
      'D Block Kamla Nagar',
      'DTC Colony',
      'Dakshini Pitampura',
      'Daryapur Kalan',
      'Daya Basti',
      'Deep Vihar',
      'Derawal Nagar',
      'Dhaka',
      'Dhirpur Village',
      'Engineer Enclave',
      'GD Block Dakshini Pitampura',
      'Gandhi Vihar',
      'Ganeshpura',
      'Garden',
      'Gautam Colony',
      'Golden Park',
      'Gopal Vihar',
      'Gopalpur Village',
      'Gulabi Bagh',
      'Guru Nanak Dev Colony',
      'Guru Teg Bahadur Nagar',
      'Hakikat Nagar',
      'Hamidpur Village',
      'Hans Residential Colony',
      'Hanuman Kunj',
      'Hardev Nagar',
      'Harsh Vihar',
      'Holambi Kalan',
      'Holambi Khurd',
      'Ibrahimpur',
      'Inderlok',
      'Indra Vihar',
      'Indraprasth Colony',
      'JJ Colony',
      'JJ Colony Wazirpur',
      'Jagatpur',
      'Jahangir Puri',
      'Jain Colony',
      'Jain Nagar',
      'Jawahar Nagar',
      'Jharoda',
      'Jharoda Majra',
      'KU Block Uttari Pitampura',
      'Kalyan Vihar',
      'Kamla Nagar',
      'Kanjhawala',
      'Karala',
      'Karawal Nagar',
      'Kashmere Gate',
      'Keshav Puram',
      'Kewal Park',
      'Khera Kalan',
      'Khera Khurd',
      'Khor',
      'Kingsway Camp',
      'Kohat Enclave',
      'Krishan Vihar',
      'Kundli',
      'Kushak Colony',
      'Laldora',
      'Lawrance Road',
      'Libas Pur',
      'Lok Vihar',
      'Loknayak Puram',
      'Lotus Enclave',
      'MCD Slum Colony',
      'Madhuban Chowk',
      'Mahendra Park',
      'Mahendru Enclave',
      'Mahindra Park',
      'Majlis Park',
      'Malka Ganj',
      'Mangalam Place',
      'Maulana Azad Society',
      'Maurice Nagar',
      'Model Town',
      'Model Town Phase 2',
      'Mukandpur Part 2',
      'Mukherjee Nagar',
      'Mukhram Garden',
      'Mukund Vihar',
      'Nai Basti',
      'Narela',
      'Narela Mandi',
      'Nathu Pura',
      'Naveen Vihar',
      'Nehru Vihar',
      'Netaji Subhash Place',
      'New Gupta Colony',
      'Nimri Colony',
      'Nirankari Colony',
      'Old Sabji Mandi',
      'Onkar Nagar',
      'Phase 1 Pocket F Sector 5',
      'Phase 1 Samaypur',
      'Pitampura',
      'Pocket 3 Sector 22',
      'Pocket 4 Sector 22 Rohini',
      'Pocket 6 Sector 21 Rohini',
      'Pocket 6 Sector 22',
      'Pocket B-5 Rohini',
      'Poorvi Pitampura',
      'Pooth Kalan',
      'Prahlad Vihar',
      'Prashant Vihar',
      'Pratap Nagar',
      'Priyadarshini Vihar',
      'Punjabi Colony',
      'Pushpanjali Enclave',
      'Railway Colony',
      'Raja Vihar',
      'Rajiv Nagar',
      'Rajiv Nagar Phase 2',
      'Rajpur Road',
      'Rajpura',
      'Rama Vihar',
      'Ramgarh',
      'Rampura',
      'Rana Park',
      'Rani Bagh',
      'Rani Khera',
      'Rithala',
      'Rohini',
      'Roop Nagar',
      'RoshNara Road',
      'Sabhapur',
      'Sabhapur Extension',
      'Sabzi Mandi',
      'Sadatpur',
      'Sainik Vihar',
      'Saint Nagar',
      'Samta Vihar',
      'Sandesh Vihar',
      'Sangam Vihar',
      'Sant Nagar',
      'Sawan Park',
      'Sector 1 Rohini',
      'Sector 11 Extension Pocket 10',
      'Sector 11 Rohini',
      'Sector 13 Rohini',
      'Sector 15 Rohini',
      'Sector 16 Rohini',
      'Sector 18 Rohini',
      'Sector 18C Rohini',
      'Sector 2 Rohini',
      'Sector 20 Rohini',
      'Sector 21 Rohini',
      'Sector 22',
      'Sector 23 Rohini',
      'Sector 24 Rohini',
      'Sector 25 Rohini',
      'Sector 26 Rohini',
      'Sector 27 Rohini',
      'Sector 28 Rohini',
      'Sector 29 Rohini',
      'Sector 3 Rohini',
      'Sector 30 Rohini',
      'Sector 31 Rohini',
      'Sector 32 Rohini',
      'Sector 33 Rohini',
      'Sector 34 Rohini',
      'Sector 35 Rohini',
      'Sector 37 Rohini',
      'Sector 39 Rohini',
      'Sector 5A Rohini',
      'Sector 7B Rohini',
      'Sector 7D',
      'Sector 7G Rohini',
      'Sector 8 Rohini',
      'Sector 9 Rohini',
      'Sector A10 Narela',
      'Sector B4 Narela',
      'Shahbad Dairy',
      'Shakurpur',
      'Shakurpur Colony',
      'Shalimar Bagh',
      'Shalimar Extension',
      'Shankarpura',
      'Sharda Niketan',
      'Sharma Colony',
      'Shastri Nagar',
      'Sher Singh Enclave',
      'Shiva Enclave',
      'Shriram Colony',
      'Siraspur',
      'Sonia Vihar',
      'St Nagar',
      'State Bank Colony',
      'Sultan Puri',
      'Swaroop Nagar',
      'Tagore Park',
      'Timar Pur',
      'Tis Hazari',
      'Tomur Colony',
      'Tri Nagar',
      'University Enclave',
      'Utsav Vihar',
      'Uttari Pitampura',
      'Vaishali',
      'Vijay Nagar',
      'Vijay Vihar Phase 1',
      'Virendar Nagar',
      'Wazirabad',
      'West Enclave',
      'West Sant Nagar',
      'West Shalimar Bagh'],
    "south-delhi": [ 'Aali Village',
      'Abul Fazal Enclave',
      'Abul Fazal Enclave 1',
      'Abul Fazal Enclave Part 1',
      'Abul Fazal Enclave Part 2',
      'Adhchini',
      'Aerocity',
      'Alaknanda',
      'Ali',
      'Aliganj',
      'Amar Colony',
      'Amar Colony E Block',
      'Amrit Nagar',
      'Amritpuri',
      'Amritpuri Block A',
      'Anand Lok',
      'Anand Niketan',
      'Ansal Satbari',
      'Ansari Nagar',
      'Aradhna Enclave',
      'Arjun Garh',
      'Arjun Nagar',
      'Ashok Vihar',
      'Ashram',
      'Asola',
      'Aya Nagar',
      'Aya Nagar Extension',
      'B Block Chhatarpur Enclave Phase 2',
      'B C R Park',
      'B5 Safdarjung Enclave',
      'Badarpur',
      'Bank Colony',
      'Basant Gaon',
      'Ber Sarai',
      'Bhagwan Nagar',
      'Bharat Nagar',
      'Bhatti Kalan',
      'Bhawani Kunj',
      'Bhogal',
      'Bk Dutt Colony',
      'Block A Defence Colony',
      'Block A Lajpat Nagar 3',
      'Block A Okhla Phase 2',
      'Block A Saket',
      'Block A1 Chattarpur',
      'Block B Greater Kailash 1',
      'Block B Sangam Vihar',
      'Block B4 Safdarjung Enclave',
      'Block C Defence Colony',
      'Block C Greater Kailash 1',
      'Block C Saket',
      'Block C Sangam Vihar',
      'Block D Chittaranjan Park',
      'Block D Hauz Khas',
      'Block D Molar Band Extension',
      'Block D Saket',
      'Block D Sangam Vihar',
      'Block E Greater Kailash 1',
      'Block E Greater Kailash 2',
      'Block E Molar Band Extension',
      'Block E Saket',
      'Block G Saket',
      'Block G Sangam Vihar',
      'Block I Chittaranjan Park',
      'Block I Sangam Vihar',
      'Block J Saket',
      'Block K Hauz Khas Enclave',
      'Block K Saket',
      'Block L Saket',
      'Block M Malviya Nagar',
      'Block M Saket',
      'Block O Chittaranjan Park',
      'Block O Lajpat Nagar 2',
      'Block P Hauz Khas',
      'Block R Greater Kailash 1',
      'Block U Green Park',
      'Block Y Hauz Khas',
      'Block Z Hauz Khas',
      'C Block Anand Niketan',
      'C Block CR Park',
      'C Block Hari Nagar',
      'CR Park',
      'Chanakya Puri',
      'Chandan Hola',
      'Chattarpur',
      'Chattarpur Enclave',
      'Chattarpur Enclave Phase 1',
      'Chattarpur Enclave Phase 2',
      'Chattarpur Extension',
      'Chhatarpur DLF Farms',
      'Chirag Delhi',
      'D Block Defence Colony',
      'DDA Flats',
      'DDA Shed',
      'Dakshinpuri',
      'Dayanand Colony',
      'Defence Colony',
      'Deoli Khanpur',
      'Dera Mandi',
      'Dera Village',
      'Devli',
      'Dharamveer Market',
      'Dr Ambedkar Nagar',
      'Duggal Colony',
      'Durga Vihar',
      'E Block East of Kailash',
      'East of Kailash',
      'Fatehpur Beri',
      'Freedom Fighter Enclave',
      'Friends Colony',
      'Friends Colony East',
      'Friends Colony West',
      'Gadaipur',
      'Garhi',
      'Ghaffar Manzil Colony',
      'Ghitorni',
      'Giri Nagar',
      'Golf Links',
      'Govind Puri',
      'Greater Kailash 1',
      'Greater Kailash 2',
      'Greater Kailash 3',
      'Greater Kailash Enclave 1',
      'Greater Kailash Enclave 2',
      'Gulmohar Enclave',
      'Gulmohar Park',
      'Haji Colony',
      'Hari Nagar',
      'Hari Nagar Ashram',
      'Hari Nagar Extension',
      'Harkesh Nagar',
      'Hauz Khas',
      'Hauz Rani',
      'Humayunpur',
      'Ina Colony',
      'Ina Market',
      'Ishwar Nagar',
      'Jaitpur',
      'Jaitpur Extension',
      'Jal Vihar',
      'Jamia Nagar',
      'Jangpura B',
      'Jasola',
      'Jasola Vihar',
      'Jawahar Park',
      'Jia Sarai',
      'Jogabai',
      'Jonapur',
      'Jor Bagh',
      'Kailash Hills',
      'Kalkaji',
      'Kalkaji Extension',
      'Kalkaji Extension Block A 8',
      'Kanchan Kunj',
      'Kapashera',
      'Khadda Colony',
      'Khan Market',
      'Khanpur Extension',
      'Khirkhi Extension',
      'Khirki Extension',
      'Kidwai Nagar',
      'Kidwai Nagar East',
      'Kilokri',
      'Kishangarh',
      'Krishna Nagar',
      'Krishna Park Colony',
      'L Block Mahipalpur',
      'Lado Sarai',
      'Lajpat Nagar 1',
      'Lajpat Nagar 2',
      'Lal Kuan',
      'Laxmi Bai Nagar',
      'Lodhi Colony',
      'Maharani Bagh',
      'Mahipalpur',
      'Mahipalpur Extension',
      'Mahipalpur Village',
      'Maidan Garhi',
      'Mandakini Enclave',
      'Mandi',
      'Masjid Moth',
      'Masjid Moth Village',
      'Masoodpur',
      'Mayfair Garden',
      'Mehrauli',
      'Mehrauli Village',
      'Mg Road',
      'Mithapur',
      'Mithapur Extension',
      'Mohammadpur',
      'Molarband',
      'Moti Bagh',
      'Munirka Enclave',
      'NRI Colony',
      'Nai Basti',
      'Naraina Village',
      'Nav Durga Vihar',
      'Neb Sarai',
      'Neb Valley',
      'Netaji Nagar',
      'New Manglapuri',
      'Nizamuddin',
      'Nizamuddin East',
      'Okhla',
      'Okhla Phase 1',
      'Okhla Vihar',
      'Om Nagar',
      'Output: Block B Lajpat Nagar 4',
      'Output: Block L-2 Devli',
      'Pamposh Enclave',
      'Panchsheel Park',
      'Phase 1 Chhatarpur Enclave',
      'Phase 6 Aya Nagar Extension',
      'Prakash Mohalla',
      'Pulpehladpur',
      'Pushp Vihar',
      'RPS Colony',
      'Rabindra Nagar',
      'Radhey Mohan Drive',
      'Rajokri',
      'Rajokri Village',
      'Rajpur Khurd',
      'Rajpur Khurd Village',
      'Raju Park',
      'Rama Krishna Puram',
      'Rangpuri',
      'Rishi Nagar',
      'S Block Greater Kailash I',
      'SDA',
      'Sadhna Enclave',
      'Safdarjung',
      'Safdarjung Development Area',
      'Saidul Ajaib',
      'Sangam Vihar',
      'Sanjay Colony',
      'Sant Nagar',
      'Sarai Kale Khan',
      'Sarita Vihar',
      'Sarojini Nagar',
      'Sarvodaya Enclave',
      'Sarvpriya Vihar',
      'Satya Niketan',
      'Saurabh Vihar',
      'Sector 12 RK Puram',
      'Sector 2 RK Puram',
      'Sector 3 RK Puram',
      'Sector 5 RK Puram',
      'Sector 6 R K Puram',
      'Sector 8 RK Puram',
      'Sector C Vasant Kunj',
      'Sector E2 Vasant Kunj',
      'Shakti Vihar',
      'Shani Bazar',
      'Shivalik Colony',
      'Shyam Nagar',
      'Siddharth Enclave',
      'Sidhartha Nagar',
      'Siri Fort',
      'Soami Nagar',
      'Som Vihar',
      'South Campus',
      'South Extension 1',
      'South Extension 2',
      'Sriniwas Puri',
      'Sultanpur',
      'Sultanpur Extension',
      'Sunlight Colony',
      'Taimoor Nagar',
      'Tajpur',
      'Tekhand',
      'Tigri',
      'Tigri Extension',
      'Tughlakabad',
      'Tyagi Mohalla',
      'Uday Park',
      'Vasant Kunj',
      'Vasant Kunj Enclave',
      'Vasant Vihar',
      'Vayusenabad',
      'Vijay Mandal Enclave',
      'Vikram Vihar',
      'Vishwakarma Colony',
      'Wazir Nagar',
      'West End Colony',
      'Westend',
      'Westend DLF Chattarpur Farms',
      'Zakir Nagar',
      'Zamrudpur'],
    "east-delhi": [  'AGCR Enclave',
      'Acharya Niketan',
      'Akshardham',
      'Ambedkar Colony',
      'Ambedkar Nagar',
      'Anand Vihar',
      'Anarkali Colony',
      'Arjun Nagar',
      'Ashok Nagar',
      'Ashok Nagar Extension',
      'Azad Nagar',
      'Babarpur',
      'Babarpur Village',
      'Bahubali Enclave',
      'Balbir Nagar',
      'Baldev Park',
      'Bank Colony',
      'Bank Enclave',
      'Bhagirathi Vihar',
      'Bhajanpura',
      'Bhola Nath Nagar',
      'Bihari Colony',
      'Block 8 Sarojini Park',
      'Block A New Ashok Nagar',
      'Block A Preet Vihar',
      'Block B New Ashok Nagar',
      'Block B Preet Vihar',
      'Block C Khajuri Khas',
      'Block C West Vinod Nagar',
      'Block C Yamuna Vihar',
      'Block D Anand Vihar',
      'Block D Ashok Nagar',
      'Block D New Ashok Nagar',
      'Block E Ashok Nagar Extension',
      'Block F Dilshad Colony',
      'Block J New Simapuri',
      'Block R Dilshad Garden',
      'Block U Shakarpur',
      'Brahmapuri',
      'C1 New Ashok Nagar',
      'Chand Bagh',
      'Chander Nagar',
      'Chander Vihar',
      'Chandu Park',
      'Chilla Sarda Bangar',
      'Chitra Vihar',
      'Common Wealth Village',
      'Dallupura',
      'Dayalpur',
      'Dayanand Vihar',
      'Dilshad Colony',
      'Dilshad Garden',
      'Durgapuri Extension',
      'East Arjun Nagar',
      'East Nathu Colony',
      'East Old Seelampur',
      'East Ram Nagar',
      'F Block Laxmi Nagar',
      'GD Colony',
      'Gagan Vihar',
      'Gandhi Nagar',
      'Ganesh Nagar',
      'Ganesh Nagar 2',
      'Ganga Vihar',
      'Gautam Puri',
      'Gautam Vihar',
      'Gazipur',
      'Geeta Colony',
      'Geeta Colony Block 8',
      'Gharoli',
      'Gharoli Extension',
      'Ghazipur Dairy Farm',
      'Ghonda Patti',
      'Ghonda Patti Chauhan',
      'Gokalpur',
      'Gokalpur East',
      'Gokalpuri',
      'Gokul Puri',
      'Gopal Park',
      'Gorakh Park',
      'Govindpura',
      'Gujarat Vihar',
      'Guru Angad Nagar',
      'Hardev Puri',
      'Hargobind Enclave',
      'Harijan Basti',
      'Harsh Vihar',
      'IP Enclave',
      'Integrated Freight Complex',
      'Jagatpuri',
      'Jagatpuri Extension',
      'Jagriti Enclave',
      'Jawala Nagar',
      'Jheel Khurenja',
      'Jhilmil Colony',
      'Jitar Nagar',
      'Johripur',
      'Joshi Colony',
      'Jyoti Colony',
      'Jyoti Nagar',
      'Kabir Nagar',
      'Kabool Nagar',
      'Kailash Nagar',
      'Kalyan Puri',
      'Kanti Nagar',
      'Kanti Nagar Extension',
      'Karawal Nagar',
      'Kardam Puri',
      'Karkardooma',
      'Khajuri Khas',
      'Khichripur',
      'Kondli',
      'Krishan Kunj',
      'Krishan Kunj Extension Part 2',
      'Krishna Nagar',
      'Krishna Nagar Extension',
      'Kundan Nagar',
      'Lalita Park',
      'Madhu Vihar',
      'Mandawali',
      'Mandoli',
      'Mandoli Extension',
      'Mangal Bazar',
      'Mansarovar Park',
      'Mayur Vihar',
      'Mayur Vihar 1',
      'Mayur Vihar Phase 1',
      'Mayur Vihar Phase 1 Extension',
      'Mayur Vihar Phase 2',
      'Mohan Park',
      'Mustafabad',
      'Nand Nagri',
      'Nehru Vihar',
      'New Ashok Nagar',
      'New Kondli',
      'New Layal Pur',
      'New Layal Pur Colony',
      'New Seelampur',
      'New Usmanpur',
      'Nirman Vihar',
      'North Ghonda',
      'Old Seelampur',
      'Old Seemapuri',
      'Pandav Nagar',
      'Paryatan Vihar',
      'Priya Enclave',
      'Radhey Shyam Park',
      'Radhey Shyam Park Extension',
      'Radheypuri',
      'Raghubarpura',
      'Railway Colony',
      'Rajdhani Enclave',
      'Rajgarh Colony',
      'Ram Nagar',
      'Ram Vihar',
      'Ramesh Park',
      'Rani Garden',
      'Rishabh Vihar',
      'Rohitash Nagar',
      'Saboli',
      'Saboli Extention',
      'Saini Enclave',
      'Sakdarpur',
      'Saket Block',
      'Savita Vihar',
      'School Block',
      'Sector C Gharoli',
      'Seelampur',
      'Shahdara',
      'Shaheed Bhagat Singh Colony',
      'Shankar Vihar',
      'Shanti Vihar',
      'Shashi Garden',
      'Shastri Nagar',
      'Shastri Park',
      'Shiv Vihar',
      'Shivaji Park',
      'Shivpuri',
      'Shreshtha Vihar',
      'Shyam Enclave',
      'Silampur',
      'Subash Vihar',
      'Subhash Park',
      'Sunder Nagri',
      'Surajmal Vihar',
      'Surya Niketan',
      'Swasthya Vihar',
      'Taharpur Village',
      'Trilokpuri',
      'Tukhmirpur',
      'Una Enclave',
      'Usmanpur',
      'Vasundhara Enclave',
      'Vigyan Lok',
      'Vijay Park',
      'Vinod Nagar',
      'Vishwas Nagar',
      'Vivek Vihar',
      'Vivek Vihar Phase 1',
      'Yojna Vihar'
    ],
    "west-delhi": ['A1 Block Paschim Vihar',
      'A2 Block Paschim Vihar',
      'A3 Block Paschim Vihar',
      'A4 Block Paschim Vihar',
      'A6 Block Paschim Vihar',
      'Adhyapak Nagar',
      'Agar Nagar',
      'Ajay Enclave',
      'Akash Vihar',
      'Aman Vihar',
      'Ambica Vihar',
      'Anand Parbat',
      'Anand Parbat Industrial Area',
      'Arihant Nagar',
      'Asha Park',
      'Ashok Nagar',
      'B2 Block Paschim Vihar',
      'B3 Block Paschim Vihar',
      'B4 Block Paschim Vihar',
      'Baba Farid Puri',
      'Bakkarwala',
      'Bali Nagar',
      'Baljeet Nagar',
      'Baprola',
      'Baprola Vihar',
      'Basai Darapur',
      'Bengali Colony',
      'Bhagwan Das Nagar',
      'Bhagwati Garden',
      'Bhagwati Garden Extension',
      'Bhera Enclave',
      'Block 11 West Patel Nagar',
      'Block 2A Nangloi Extension',
      'Block 31 West Patel Nagar',
      'Block 6 Ramesh Nagar',
      'Block 8 Subhash Nagar',
      'Block A',
      'Block A 1 Uttam Nagar',
      'Block A 2 Uttam Nagar',
      'Block A 3 Uttam Nagar',
      'Block A Kiran Garden',
      'Block A Panchvati Apartment',
      'Block B Patel Nagar',
      'Block B Rajouri Garden',
      'Block B Vijay Enclave',
      'Block BA Tagore Garden',
      'Block BC Mianwali Nagar',
      'Block C Mansa Ram Park',
      'Block D Janakpuri',
      'Block D Ram Datt Enclave',
      'Block D1 Uttam Nagar',
      'Block DG 1 Vikaspuri',
      'Block E Mangolpuri',
      'Block E Shyam Vihar Phase 1',
      'Block F Hari Nagar',
      'Block F Rajouri Garden',
      'Block F Vikas Puri',
      'Block FA Mansarover Garden',
      'Block G Naraina Vihar',
      'Block G Uttam Nagar',
      'Block GH 14 Paschim Vihar',
      'Block GH 4 Meera Bagh',
      'Block GH 5 Meera Bagh',
      'Block H-3 Vikaspuri',
      'Block J Rajouri Garden',
      'Block J West Sagarpur',
      'Block JG 2 Vikaspuri',
      'Block L JJ Colony No 3',
      'Block M Vikas Puri',
      'Block RZ Kali Nagar',
      'Block U Mangolpuri',
      'Block U Nihal Vihar',
      'Block Va Janakpuri',
      'Block X JJ Colony No 3',
      'Block de Tagore Garden',
      'Bodella',
      'C Block Janakpuri',
      'C Block Vikaspuri',
      'Camp No 4 Jwalapuri',
      'Chanakya Place',
      'Chanakya Place 1',
      'Chanchal Park',
      'Chand Nagar',
      'Chandan Vihar',
      'Chander Nagar',
      'Chaukhandi',
      'D Block Vikaspuri',
      'D Block West Patel Nagar',
      'DTC Colony Shadipur',
      'Dasghara',
      'Dashrath Puri',
      'Deenpur',
      'Deepak Vihar',
      'Dharampura',
      'Dichaon Kalan',
      'Dindarpur',
      'Durga Puri',
      'Dwarka Mor',
      'East Patel Nagar',
      'F Block Vikaspuri',
      'F Block Vishnu Garden',
      'F-2 Block Jai Vihar',
      'Fateh Nagar',
      'G Block Vikaspuri',
      'Gandhi Market',
      'Ganesh Nagar',
      'Ghevra',
      'Gopal Extension 2',
      'Gopal Nagar',
      'Gopal Nagar Extension',
      'Gopal Nagar Extn 1',
      'Guru Harkishan Nagar',
      'Guru Nanak Nagar',
      'Gurunanak Pura',
      'Hari Enclave',
      'Hari Nagar',
      'Harphool Vihar',
      'Hastsal',
      'Hind Nagar',
      'Inder Enclave',
      'Inderpuri',
      'Indira Park',
      'Indra Park',
      'J Block Vikaspuri',
      'JJ Colony',
      'JJ Colony Nangloi',
      'Jaffarpur Kalan',
      'Jai Vihar',
      'Jaidev Park',
      'Jain Colony',
      'Janakpuri',
      'Jharoda Kalan',
      'Kali Nagar',
      'Kamruddin Nagar',
      'Karampura',
      'Kashmiri Colony',
      'Khaira',
      'Khayala',
      'Khera Dabar',
      'Kiran Garden',
      'Kirari Extension',
      'Kirari Suleman Nagar',
      'Kirti Nagar',
      'Krishna Apartment',
      'Krishna Park Extension',
      'Krishna Puri',
      'Kunwar Singh Nagar',
      'L Block Hari Nagar',
      'Laxmi Vihar',
      'Lok Nayak Puram',
      'MBS Nagar',
      'Madanpur Dabas',
      'Madipur',
      'Mahaveer Nagar',
      'Mahavir Enclave',
      'Mahavir Enclave Part 1',
      'Mahavir Enclave Part 2',
      'Mahavir Enclave Part 3',
      'Manak Vihar',
      'Manas Kunj',
      'Manglapuri',
      'Mangol Puri Industrial Area Phase 1',
      'Mangolpur Khurd',
      'Mangolpuri',
      'Mangolpuri Industrial Area',
      'Mansa Ram Park',
      'Mansarovar Garden',
      'Masudabad',
      'Matiala',
      'Matiala Extension',
      'Mayapuri',
      'Mayapuri Industrial Area Phase 1',
      'Mayapuri Industrial Area Phase 2',
      'Meenakshi Garden',
      'Meera Bagh',
      'Mianwali Nagar',
      'Milk Scheme Colony',
      'Mirzapur',
      'Mohan Garden',
      'Moti Nagar',
      'Mubarakpur Dabas',
      'Mubarkpur',
      'Mukerjee Park',
      'Mukhram Park Extension',
      'Mundka',
      'Najafgarh',
      'Najafgarh Road',
      'Nanak Pura',
      'Nanda Block',
      'Nangal Raya',
      'Nangli Sakrawati',
      'Nangloi',
      'Nangloi Extension',
      'Nanhey Park',
      'Naraina',
      'Naraina Industrial Area Phase 1',
      'Naraina Vihar',
      'Narang Colony',
      'Nawada',
      'Nawada Extension',
      'New Patel Nagar',
      'New Rohtak Road',
      'Nihal Vihar',
      'Nilothi',
      'Nilothi Extn',
      'Om Vihar',
      'Om Vihar Extension',
      'Om Vihar Phase 3',
      'Palam Colony',
      'Palam Enclave',
      'Pankha Road',
      'Param Puri',
      'Paschim Puri',
      'Paschim Vihar',
      'Patel Nagar',
      'Peeragarhi',
      'Phase 1 Pocket B Mangolpuri Industrial Area',
      'Phase 4 Om Vihar',
      'Phase 5 Om Vihar',
      'Pratap Enclave',
      'Pratap Vihar',
      'Prem Nagar',
      'Prem Nagar 3',
      'Press Colony',
      'Punjabi Bagh',
      'Punjabi Bagh Extension',
      'Punjabi Basti',
      'Raghubir Nagar',
      'Raja Garden',
      'Rajapuri',
      'Rajasthan Colony',
      'Rajouri Garden',
      'Ram Datt Enclave',
      'Ram Park',
      'Rama Park',
      'Ramchander Enclave',
      'Ranaji Enclave',
      'Ranhola',
      'Ranhola Extension',
      'Rani Bagh',
      'Ranjeet Nagar',
      'Ratan Park',
      'Rawta More',
      'Razapur Khurd',
      'Reserve Bank Enclave',
      'Roshanpura',
      'Sagarpur',
      'Sainik Enclave',
      'Sainik Nagar',
      'Sainik Vihar',
      'Saraswati Garden',
      'Shahpura',
      'Shiv Nagar',
      'Shiv Ram Park Extention 2',
      'Shiv Vihar',
      'Shyam Nagar',
      'Shyam Vihar',
      'Shyam Vihar 1',
      'Shyam Vihar Phase 1',
      'Sitapuri',
      'South Patel Nagar',
      'Subhash Park',
      'Sultanpur Majra Village',
      'Sultanpuri',
      'T Extension',
      'Tagore Garden',
      'Tihar Village',
      'Tikri Kalan',
      'Tilak Nagar',
      'Tilangpur Kotla',
      'Todapur',
      'Tyagi Vihar',
      'Udyog Nagar',
      'Uttam Nagar',
      'Vaishali Colony',
      'Vani Vihar',
      'Vashist Park',
      'Vijay Enclave',
      'Vijay Vihar',
      'Vikas Nagar',
      'Vikas Puri',
      'Vikas Vihar',
      'Vikaspuri',
      'Vikrant Enclave',
      'Vipin Garden',
      'Vipin Garden Extension',
      'Vipin Garden Extension North Block',
      'Vishnu Garden',
      'Vishwas Park',
      'Ware Housing Scheme',
      'West Patel Nagar',
      'Zaildar Enclave'],
  };

  const createSlug = (name) =>
    name.toLowerCase().replace(/\s+/g, "-");

  const locations = zones[zone] || [];

  const formattedZone = zone
    ?.replace(/-/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());

  return (
   <section className="min-h-screen bg-white py-16">
  <div className="max-w-7xl mx-auto px-6">

    {/* HEADER */}
    <div className="text-center mb-12">

      <h1 className="text-3xl md:text-4xl font-bold text-red-600 mb-4">
        Real Estate in {formattedZone}
      </h1>

      <p className="text-gray-600 max-w-2xl mx-auto">
        Browse verified property dealers across {formattedZone}.
      </p>

    </div>

    {/* LIST */}
    <ul className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-y-4 gap-x-8 text-gray-700">

      {locations.map((location, index) => (
        <li key={index}>
          <Link
            href={`/delhi/${createSlug(location)}`}
            className="transition font-medium hover:text-red-600 hover:font-bold hover:underline"

          >
            Property Dealer in {location}
          </Link>
        </li>
      ))}

    </ul>

  </div>
</section>


  );
}
