"use client";

import Breadcrumb from "@/templates/design5/components/Breadcrumb";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useState, useEffect } from "react";
export default function ZonePage() {
  const params = useParams();
 const zone = params?.zone;
  
const [isMobile, setIsMobile] = useState(false);
const [showAll, setShowAll] = useState(false);
  const zones = {
    "central-delhi": ['Ajmeri Gate Central Delhi',
      'Amrita Shergill Marg Central Delhi',
      'Arya Nagar Central Delhi',
      'Asaf Ali Road Central Delhi',
      'Ashoka Road Central Delhi',
      'Bara Hindu Rao Central Delhi',
      'Barakhamba Central Delhi',
      'Barakhamba Road Central Delhi',
      'Beadon Pura Central Delhi',
      'Bengali Market Central Delhi',
      'Bhagirath Palace Central Delhi',
      'Block 13 WEA Central Delhi',
      'Block 14 WEA Central Delhi',
      'Block 16 WEA Central Delhi',
      'Block 16A WEA Central Delhi',
      'Block 22B Dev Nagar Central Delhi',
      'Block 29 Regar Pura Central Delhi',
      'Block 44Q Beadon Pura Central Delhi',
      'Block 6 WEA Central Delhi',
      'Block 6A WEA Central Delhi',
      'Block 8 WEA Central Delhi',
      'Block 8A WEA Central Delhi',
      'Block B New Rajinder Nagar Central Delhi',
      'Block E Jhandewalan Extension Central Delhi',
      'Channa Market Central Delhi',
      'Chawri Bazar Central Delhi',
      'Chhippy Wada Central Delhi',
      'Chuna Mandi Central Delhi',
      'Connaught Place Central Delhi' ,
      'Daryaganj Central Delhi',
      'Deputy Ganj Central Delhi',
      'Dev Nagar Central Delhi',
      'Diz Area Central Delhi',
      'Hauz Qazi Central Delhi',
      'IP Estate Central Delhi',
      'India Gate Central Delhi',
      'Ito Central Delhi',
      'Jama Masjid Central Delhi',
      'Kaka Nagar Central Delhi',
      'Kalan Mahal Central Delhi',
      'Kamla Market Central Delhi',
      'Khari Baoli Central Delhi',
      'Kishan Ganj Central Delhi',
      'Krishna Nagar Central Delhi',
      'Malcha Central Delhi',
      'Mandi House Central Delhi',
      'Multani Dhanda Central Delhi',
      'Naya Bazar Central Delhi',
      'New Rajendra Nagar Central Delhi',
      'Nizamuddin West Central Delhi',
      'Old Rajinder Nagar',
      'Padam Nagar Central Delhi',
      'Pahari Dhiraj Central Delhi',
      'Pragati Maidan Central Delhi',
      'Prasad Nagar Central Delhi',
      'Press Enclave Central Delhi',
      'Prithviraj Road Central Delhi',
      'Pusa Road Central Delhi',
      'Raisina Hills Central Delhi',
      'Rajender Nagar Central Delhi',
      'Rajendra Park Central Delhi',
      'Rajinder Nagar Central Delhi',
      'Rajiv Chowk Central Delhi',
      'Regar Pura Central Delhi',
      'Sant Nagar Central Delhi',
      'Sarai Rohilla Central Delhi',
      'Shaheed Bhagat Singh Marg Central Delhi',
      'Sita Ram Bazar Central Delhi',
      'Sunder Nagar Central Delhi',
      'Swami Dayanand Colony Central Delhi',
      'Teliwara Central Delhi',
      'Tilak Marg Central Delhi',
      'Turkman Gate Central Delhi',
      'Vikram Nagar Central Delhi'],


    "north-delhi": [
"Adarsh Nagar North Delhi",
"Adarsh Nagar Extension North Delhi",
"Ajit Vihar North Delhi",
"Alipur North Delhi",
"Amrit Vihar North Delhi",
"Anand Vihar North Delhi",
"Ashok Vihar North Delhi",
"Ashok Vihar Phase 1 North Delhi",
"Ashok Vihar Phase 2 North Delhi",
"Ashok Vihar Phase 3 North Delhi",
"Ashok Vihar Phase 4 North Delhi",
"Avantika Pocket E Vijay Vihar Phase 2 North Delhi",
"Avantika Sector 1 North Delhi",
"Azad Market North Delhi",
"Azadpur North Delhi",
"B Block Baba Colony North Delhi",
"B Block Kaushik Enclave North Delhi",
"B Block Prashant Vihar North Delhi",
"B Block Shastri Nagar North Delhi",
"B Block Virendar Nagar North Delhi",
"B Block West Sant Nagar North Delhi",
"BM Block West Shalimar Bagh North Delhi",
"Baba Colony North Delhi",
"Badli North Delhi",
"Badli Industrial Area North Delhi",
"Bakhtawarpur North Delhi",
"Banarsi Das Estate North Delhi",
"Bankner Village North Delhi",
"Bawana North Delhi",
"Begam Pur North Delhi",
"Begam Vihar North Delhi",
"Begampur North Delhi",
"Begampur Extension North Delhi",
"Bengali Colony North Delhi",
"Bhai Parmanand Colony North Delhi",
"Bhalswa North Delhi",
"Bhalswa Dairy North Delhi",
"Bharat Nagar North Delhi",
"Bhorgarh North Delhi",
"Block A West Sant Nagar North Delhi",
"Block B Pocket C Sector 1 Rohini North Delhi",
"Block B, Sector 17, Rohini North Delhi",
"Block C Vijay Vihar Phase 1 North Delhi",
"Block D Shastri Nagar North Delhi",
"Block E Saraswati Vihar North Delhi",
"Block E Shastri Nagar North Delhi",
"Block E2 Shastri Nagar North Delhi",
"Block F-1U Uttari Pitampura North Delhi",
"Block Fu Uttari Pitampura North Delhi",
"Block G, Sector 16 Rohini North Delhi",
"Block L Shastri Nagar North Delhi",
"Budh Vihar North Delhi",
"Budh Vihar Phase 1 North Delhi",
"Budh Vihar Phase 2 North Delhi",
"Budhh Vihar Market North Delhi",
"Budhpur North Delhi",
"Burari North Delhi",
"Burari Garhi North Delhi",
"C6 Keshav Puram North Delhi",
"CC Colony North Delhi",
"Chandan Vihar North Delhi",
"Civil Lines North Delhi",
"D Block Kamla Nagar North Delhi",
"DTC Colony North Delhi",
"Dakshini Pitampura North Delhi",
"Daryapur Kalan North Delhi",
"Daya Basti North Delhi",
"Deep Vihar North Delhi",
"Derawal Nagar North Delhi",
"Dhaka North Delhi",
"Dhirpur Village North Delhi",
"Engineer Enclave North Delhi",
"GD Block Dakshini Pitampura North Delhi",
"Gandhi Vihar North Delhi",
"Ganeshpura North Delhi",
"Garden North Delhi",
"Gautam Colony North Delhi",
"Golden Park North Delhi",
"Gopal Vihar North Delhi",
"Gopalpur Village North Delhi",
"Gulabi Bagh North Delhi",
"Guru Nanak Dev Colony North Delhi",
"Guru Teg Bahadur Nagar North Delhi",
"Hakikat Nagar North Delhi",
"Hamidpur Village North Delhi",
"Hans Residential Colony North Delhi",
"Hanuman Kunj North Delhi",
"Hardev Nagar North Delhi",
"Harsh Vihar North Delhi",
"Holambi Kalan North Delhi",
"Holambi Khurd North Delhi",
"Ibrahimpur North Delhi",
"Inderlok North Delhi",
"Indra Vihar North Delhi",
"Indraprasth Colony North Delhi",
"JJ Colony North Delhi",
"JJ Colony Wazirpur North Delhi",
"Jagatpur North Delhi",
"Jahangir Puri North Delhi",
"Jain Colony North Delhi",
"Jain Nagar North Delhi",
"Jawahar Nagar North Delhi",
"Jharoda North Delhi",
"Jharoda Majra North Delhi",
"KU Block Uttari Pitampura North Delhi",
"Kalyan Vihar North Delhi",
"Kamla Nagar North Delhi",
"Kanjhawala North Delhi",
"Karala North Delhi",
"Karawal Nagar North Delhi",
"Kashmere Gate North Delhi",
"Keshav Puram North Delhi",
"Kewal Park North Delhi",
"Khera Kalan North Delhi",
"Khera Khurd North Delhi",
"Khor North Delhi",
"Kingsway Camp North Delhi",
"Kohat Enclave North Delhi",
"Krishan Vihar North Delhi",
"Kundli North Delhi",
"Kushak Colony North Delhi",
"Laldora North Delhi",
"Lawrance Road North Delhi",
"Libas Pur North Delhi",
"Lok Vihar North Delhi",
"Loknayak Puram North Delhi",
"Lotus Enclave North Delhi",
"MCD Slum Colony North Delhi",
"Madhuban Chowk North Delhi",
"Mahendra Park North Delhi",
"Mahendru Enclave North Delhi",
"Mahindra Park North Delhi",
"Majlis Park North Delhi",
"Malka Ganj North Delhi",
"Mangalam Place North Delhi",
"Maulana Azad Society North Delhi",
"Maurice Nagar North Delhi",
"Model Town North Delhi",
"Model Town Phase 2 North Delhi",
"Mukandpur Part 2 North Delhi",
"Mukherjee Nagar North Delhi",
"Mukhram Garden North Delhi",
"Mukund Vihar North Delhi",
"Nai Basti North Delhi",
"Narela North Delhi",
"Narela Mandi North Delhi",
"Nathu Pura North Delhi",
"Naveen Vihar North Delhi",
"Nehru Vihar North Delhi",
"Netaji Subhash Place North Delhi",
"New Gupta Colony North Delhi",
"Nimri Colony North Delhi",
"Nirankari Colony North Delhi",
"Old Sabji Mandi North Delhi",
"Onkar Nagar North Delhi",
"Phase 1 Pocket F Sector 5 North Delhi",
"Phase 1 Samaypur North Delhi",
"Pitampura North Delhi",
"Pocket 3 Sector 22 North Delhi",
"Pocket 4 Sector 22 Rohini North Delhi",
"Pocket 6 Sector 21 Rohini North Delhi",
"Pocket 6 Sector 22 North Delhi",
"Pocket B-5 Rohini North Delhi",
"Poorvi Pitampura North Delhi",
"Pooth Kalan North Delhi",
"Prahlad Vihar North Delhi",
"Prashant Vihar North Delhi",
"Pratap Nagar North Delhi",
"Priyadarshini Vihar North Delhi",
"Punjabi Colony North Delhi",
"Pushpanjali Enclave North Delhi",
"Railway Colony North Delhi",
"Raja Vihar North Delhi",
"Rajiv Nagar North Delhi",
"Rajiv Nagar Phase 2 North Delhi",
"Rajpur Road North Delhi",
"Rajpura North Delhi",
"Rama Vihar North Delhi",
"Ramgarh North Delhi",
"Rampura North Delhi",
"Rana Park North Delhi",
"Rani Bagh North Delhi",
"Rani Khera North Delhi",
"Rithala North Delhi",
"Rohini North Delhi",
"Roop Nagar North Delhi",
"RoshNara Road North Delhi",
"Sabhapur North Delhi",
"Sabhapur Extension North Delhi",
"Sabzi Mandi North Delhi",
"Sadatpur North Delhi",
"Sainik Vihar North Delhi",
"Saint Nagar North Delhi",
"Samta Vihar North Delhi",
"Sandesh Vihar North Delhi",
"Sangam Vihar North Delhi",
"Sant Nagar North Delhi",
"Sawan Park North Delhi",
"Sector 1 Rohini North Delhi",
"Sector 11 Extension Pocket 10 North Delhi",
"Sector 11 Rohini North Delhi",
"Sector 13 Rohini North Delhi",
"Sector 15 Rohini North Delhi",
"Sector 16 Rohini North Delhi",
"Sector 18 Rohini North Delhi",
"Sector 18C Rohini North Delhi",
"Sector 2 Rohini North Delhi",
"Sector 20 Rohini North Delhi",
"Sector 21 Rohini North Delhi",
"Sector 22 North Delhi",
"Sector 23 Rohini North Delhi",
"Sector 24 Rohini North Delhi",
"Sector 25 Rohini North Delhi",
"Sector 26 Rohini North Delhi",
"Sector 27 Rohini North Delhi",
"Sector 28 Rohini North Delhi",
"Sector 29 Rohini North Delhi",
"Sector 3 Rohini North Delhi",
"Sector 30 Rohini North Delhi",
"Sector 31 Rohini North Delhi",
"Sector 32 Rohini North Delhi",
"Sector 33 Rohini North Delhi",
"Sector 34 Rohini North Delhi",
"Sector 35 Rohini North Delhi",
"Sector 37 Rohini North Delhi",
"Sector 39 Rohini North Delhi",
"Sector 5A Rohini North Delhi",
"Sector 7B Rohini North Delhi",
"Sector 7D North Delhi",
"Sector 7G Rohini North Delhi",
"Sector 8 Rohini North Delhi",
"Sector 9 Rohini North Delhi",
"Sector A10 Narela North Delhi",
"Sector B4 Narela North Delhi",
"Shahbad Dairy North Delhi",
"Shakurpur North Delhi",
"Shakurpur Colony North Delhi",
"Shalimar Bagh North Delhi",
"Shalimar Extension North Delhi",
"Shankarpura North Delhi",
"Sharda Niketan North Delhi",
"Sharma Colony North Delhi",
"Shastri Nagar North Delhi",
"Sher Singh Enclave North Delhi",
"Shiva Enclave North Delhi",
"Shriram Colony North Delhi",
"Siraspur North Delhi",
"Sonia Vihar North Delhi",
"St Nagar North Delhi",
"State Bank Colony North Delhi",
"Sultan Puri North Delhi",
"Swaroop Nagar North Delhi",
"Tagore Park North Delhi",
"Timar Pur North Delhi",
"Tis Hazari North Delhi",
"Tomur Colony North Delhi",
"Tri Nagar North Delhi",
"University Enclave North Delhi",
"Utsav Vihar North Delhi",
"Uttari Pitampura North Delhi",
"Vaishali North Delhi",
"Vijay Nagar North Delhi",
"Vijay Vihar Phase 1 North Delhi",
"Virendar Nagar North Delhi",
"Wazirabad North Delhi",
"West Enclave North Delhi",
"West Sant Nagar North Delhi",
"West Shalimar Bagh North Delhi"
],
    "south-delhi": [
"Aali Village South Delhi",
"Abul Fazal Enclave South Delhi",
"Abul Fazal Enclave 1 South Delhi",
"Abul Fazal Enclave Part 1 South Delhi",
"Abul Fazal Enclave Part 2 South Delhi",
"Adhchini South Delhi",
"Aerocity South Delhi",
"Alaknanda South Delhi",
"Ali South Delhi",
"Aliganj South Delhi",
"Amar Colony South Delhi",
"Amar Colony E Block South Delhi",
"Amrit Nagar South Delhi",
"Amritpuri South Delhi",
"Amritpuri Block A South Delhi",
"Anand Lok South Delhi",
"Anand Niketan South Delhi",
"Ansal Satbari South Delhi",
"Ansari Nagar South Delhi",
"Aradhna Enclave South Delhi",
"Arjun Garh South Delhi",
"Arjun Nagar South Delhi",
"Ashok Vihar South Delhi",
"Ashram South Delhi",
"Asola South Delhi",
"Aya Nagar South Delhi",
"Aya Nagar Extension South Delhi",
"B Block Chhatarpur Enclave Phase 2 South Delhi",
"B C R Park South Delhi",
"B5 Safdarjung Enclave South Delhi",
"Badarpur South Delhi",
"Bank Colony South Delhi",
"Basant Gaon South Delhi",
"Ber Sarai South Delhi",
"Bhagwan Nagar South Delhi",
"Bharat Nagar South Delhi",
"Bhatti Kalan South Delhi",
"Bhawani Kunj South Delhi",
"Bhogal South Delhi",
"Bk Dutt Colony South Delhi",
"Block A Defence Colony South Delhi",
"Block A Lajpat Nagar 3 South Delhi",
"Block A Okhla Phase 2 South Delhi",
"Block A Saket South Delhi",
"Block A1 Chattarpur South Delhi",
"Block B Greater Kailash 1 South Delhi",
"Block B Sangam Vihar South Delhi",
"Block B4 Safdarjung Enclave South Delhi",
"Block C Defence Colony South Delhi",
"Block C Greater Kailash 1 South Delhi",
"Block C Saket South Delhi",
"Block C Sangam Vihar South Delhi",
"Block D Chittaranjan Park South Delhi",
"Block D Hauz Khas South Delhi",
"Block D Molar Band Extension South Delhi",
"Block D Saket South Delhi",
"Block D Sangam Vihar South Delhi",
"Block E Greater Kailash 1 South Delhi",
"Block E Greater Kailash 2 South Delhi",
"Block E Molar Band Extension South Delhi",
"Block E Saket South Delhi",
"Block G Saket South Delhi",
"Block G Sangam Vihar South Delhi",
"Block I Chittaranjan Park South Delhi",
"Block I Sangam Vihar South Delhi",
"Block J Saket South Delhi",
"Block K Hauz Khas Enclave South Delhi",
"Block K Saket South Delhi",
"Block L Saket South Delhi",
"Block M Malviya Nagar South Delhi",
"Block M Saket South Delhi",
"Block O Chittaranjan Park South Delhi",
"Block O Lajpat Nagar 2 South Delhi",
"Block P Hauz Khas South Delhi",
"Block R Greater Kailash 1 South Delhi",
"Block U Green Park South Delhi",
"Block Y Hauz Khas South Delhi",
"Block Z Hauz Khas South Delhi",
"C Block Anand Niketan South Delhi",
"C Block CR Park South Delhi",
"C Block Hari Nagar South Delhi",
"CR Park South Delhi",
"Chanakya Puri South Delhi",
"Chandan Hola South Delhi",
"Chattarpur South Delhi",
"Chattarpur Enclave South Delhi",
"Chattarpur Enclave Phase 1 South Delhi",
"Chattarpur Enclave Phase 2 South Delhi",
"Chattarpur Extension South Delhi",
"Chhatarpur DLF Farms South Delhi",
"Chirag Delhi South Delhi",
"D Block Defence Colony South Delhi",
"DDA Flats South Delhi",
"DDA Shed South Delhi",
"Dakshinpuri South Delhi",
"Dayanand Colony South Delhi",
"Defence Colony South Delhi",
"Deoli Khanpur South Delhi",
"Dera Mandi South Delhi",
"Dera Village South Delhi",
"Devli South Delhi",
"Dharamveer Market South Delhi",
"Dr Ambedkar Nagar South Delhi",
"Duggal Colony South Delhi",
"Durga Vihar South Delhi",
"E Block East of Kailash South Delhi",
"East of Kailash South Delhi",
"Fatehpur Beri South Delhi",
"Freedom Fighter Enclave South Delhi",
"Friends Colony South Delhi",
"Friends Colony East South Delhi",
"Friends Colony West South Delhi",
"Gadaipur South Delhi",
"Garhi South Delhi",
"Ghaffar Manzil Colony South Delhi",
"Ghitorni South Delhi",
"Giri Nagar South Delhi",
"Golf Links South Delhi",
"Govind Puri South Delhi",
"Greater Kailash 1 South Delhi",
"Greater Kailash 2 South Delhi",
"Greater Kailash 3 South Delhi",
"Greater Kailash Enclave 1 South Delhi",
"Greater Kailash Enclave 2 South Delhi",
"Gulmohar Enclave South Delhi",
"Gulmohar Park South Delhi",
"Haji Colony South Delhi",
"Hari Nagar South Delhi",
"Hari Nagar Ashram South Delhi",
"Hari Nagar Extension South Delhi",
"Harkesh Nagar South Delhi",
"Hauz Khas South Delhi",
"Hauz Rani South Delhi",
"Humayunpur South Delhi",
"Ina Colony South Delhi",
"Ina Market South Delhi",
"Ishwar Nagar South Delhi",
"Jaitpur South Delhi",
"Jaitpur Extension South Delhi",
"Jal Vihar South Delhi",
"Jamia Nagar South Delhi",
"Jangpura B South Delhi",
"Jasola South Delhi",
"Jasola Vihar South Delhi",
"Jawahar Park South Delhi",
"Jia Sarai South Delhi",
"Jogabai South Delhi",
"Jonapur South Delhi",
"Jor Bagh South Delhi",
"Kailash Hills South Delhi",
"Kalkaji South Delhi",
"Kalkaji Extension South Delhi",
"Kalkaji Extension Block A 8 South Delhi",
"Kanchan Kunj South Delhi",
"Kapashera South Delhi",
"Khadda Colony South Delhi",
"Khan Market South Delhi",
"Khanpur Extension South Delhi",
"Khirkhi Extension South Delhi",
"Khirki Extension South Delhi",
"Kidwai Nagar South Delhi",
"Kidwai Nagar East South Delhi",
"Kilokri South Delhi",
"Kishangarh South Delhi",
"Krishna Nagar South Delhi",
"Krishna Park Colony South Delhi",
"L Block Mahipalpur South Delhi",
"Lado Sarai South Delhi",
"Lajpat Nagar 1 South Delhi",
"Lajpat Nagar 2 South Delhi",
"Lal Kuan South Delhi",
"Laxmi Bai Nagar South Delhi",
"Lodhi Colony South Delhi",
"Maharani Bagh South Delhi",
"Mahipalpur South Delhi",
"Mahipalpur Extension South Delhi",
"Mahipalpur Village South Delhi",
"Maidan Garhi South Delhi",
"Mandakini Enclave South Delhi",
"Mandi South Delhi",
"Masjid Moth South Delhi",
"Masjid Moth Village South Delhi",
"Masoodpur South Delhi",
"Mayfair Garden South Delhi",
"Mehrauli South Delhi",
"Mehrauli Village South Delhi",
"Mg Road South Delhi",
"Mithapur South Delhi",
"Mithapur Extension South Delhi",
"Mohammadpur South Delhi",
"Molarband South Delhi",
"Moti Bagh South Delhi",
"Munirka Enclave South Delhi",
"NRI Colony South Delhi",
"Nai Basti South Delhi",
"Naraina Village South Delhi",
"Nav Durga Vihar South Delhi",
"Neb Sarai South Delhi",
"Neb Valley South Delhi",
"Netaji Nagar South Delhi",
"New Manglapuri South Delhi",
"Nizamuddin South Delhi",
"Nizamuddin East South Delhi",
"Okhla South Delhi",
"Okhla Phase 1 South Delhi",
"Okhla Vihar South Delhi",
"Om Nagar South Delhi",
"Output: Block B Lajpat Nagar 4 South Delhi",
"Output: Block L-2 Devli South Delhi",
"Pamposh Enclave South Delhi",
"Panchsheel Park South Delhi",
"Phase 1 Chhatarpur Enclave South Delhi",
"Phase 6 Aya Nagar Extension South Delhi",
"Prakash Mohalla South Delhi",
"Pulpehladpur South Delhi",
"Pushp Vihar South Delhi",
"RPS Colony South Delhi",
"Rabindra Nagar South Delhi",
"Radhey Mohan Drive South Delhi",
"Rajokri South Delhi",
"Rajokri Village South Delhi",
"Rajpur Khurd South Delhi",
"Rajpur Khurd Village South Delhi",
"Raju Park South Delhi",
"Rama Krishna Puram South Delhi",
"Rangpuri South Delhi",
"Rishi Nagar South Delhi",
"S Block Greater Kailash I South Delhi",
"SDA South Delhi",
"Sadhna Enclave South Delhi",
"Safdarjung South Delhi",
"Safdarjung Development Area South Delhi",
"Saidul Ajaib South Delhi",
"Sangam Vihar South Delhi",
"Sanjay Colony South Delhi",
"Sant Nagar South Delhi",
"Sarai Kale Khan South Delhi",
"Sarita Vihar South Delhi",
"Sarojini Nagar South Delhi",
"Sarvodaya Enclave South Delhi",
"Sarvpriya Vihar South Delhi",
"Satya Niketan South Delhi",
"Saurabh Vihar South Delhi",
"Sector 12 RK Puram South Delhi",
"Sector 2 RK Puram South Delhi",
"Sector 3 RK Puram South Delhi",
"Sector 5 RK Puram South Delhi",
"Sector 6 R K Puram South Delhi",
"Sector 8 RK Puram South Delhi",
"Sector C Vasant Kunj South Delhi",
"Sector E2 Vasant Kunj South Delhi",
"Shakti Vihar South Delhi",
"Shani Bazar South Delhi",
"Shivalik Colony South Delhi",
"Shyam Nagar South Delhi",
"Siddharth Enclave South Delhi",
"Sidhartha Nagar South Delhi",
"Siri Fort South Delhi",
"Soami Nagar South Delhi",
"Som Vihar South Delhi",
"South Campus South Delhi",
"South Extension 1 South Delhi",
"South Extension 2 South Delhi",
"Sriniwas Puri South Delhi",
"Sultanpur South Delhi",
"Sultanpur Extension South Delhi",
"Sunlight Colony South Delhi",
"Taimoor Nagar South Delhi",
"Tajpur South Delhi",
"Tekhand South Delhi",
"Tigri South Delhi",
"Tigri Extension South Delhi",
"Tughlakabad South Delhi",
"Tyagi Mohalla South Delhi",
"Uday Park South Delhi",
"Vasant Kunj South Delhi",
"Vasant Kunj Enclave South Delhi",
"Vasant Vihar South Delhi",
"Vayusenabad South Delhi",
"Vijay Mandal Enclave South Delhi",
"Vikram Vihar South Delhi",
"Vishwakarma Colony South Delhi",
"Wazir Nagar South Delhi",
"West End Colony South Delhi",
"Westend South Delhi",
"Westend DLF Chattarpur Farms South Delhi",
"Zakir Nagar South Delhi",
"Zamrudpur South Delhi"
],
    "east-delhi": [
"AGCR Enclave East Delhi",
"Acharya Niketan East Delhi",
"Akshardham East Delhi",
"Ambedkar Colony East Delhi",
"Ambedkar Nagar East Delhi",
"Anand Vihar East Delhi",
"Anarkali Colony East Delhi",
"Arjun Nagar East Delhi",
"Ashok Nagar East Delhi",
"Ashok Nagar Extension East Delhi",
"Azad Nagar East Delhi",
"Babarpur East Delhi",
"Babarpur Village East Delhi",
"Bahubali Enclave East Delhi",
"Balbir Nagar East Delhi",
"Baldev Park East Delhi",
"Bank Colony East Delhi",
"Bank Enclave East Delhi",
"Bhagirathi Vihar East Delhi",
"Bhajanpura East Delhi",
"Bhola Nath Nagar East Delhi",
"Bihari Colony East Delhi",
"Block 8 Sarojini Park East Delhi",
"Block A New Ashok Nagar East Delhi",
"Block A Preet Vihar East Delhi",
"Block B New Ashok Nagar East Delhi",
"Block B Preet Vihar East Delhi",
"Block C Khajuri Khas East Delhi",
"Block C West Vinod Nagar East Delhi",
"Block C Yamuna Vihar East Delhi",
"Block D Anand Vihar East Delhi",
"Block D Ashok Nagar East Delhi",
"Block D New Ashok Nagar East Delhi",
"Block E Ashok Nagar Extension East Delhi",
"Block F Dilshad Colony East Delhi",
"Block J New Simapuri East Delhi",
"Block R Dilshad Garden East Delhi",
"Block U Shakarpur East Delhi",
"Brahmapuri East Delhi",
"C1 New Ashok Nagar East Delhi",
"Chand Bagh East Delhi",
"Chander Nagar East Delhi",
"Chander Vihar East Delhi",
"Chandu Park East Delhi",
"Chilla Sarda Bangar East Delhi",
"Chitra Vihar East Delhi",
"Common Wealth Village East Delhi",
"Dallupura East Delhi",
"Dayalpur East Delhi",
"Dayanand Vihar East Delhi",
"Dilshad Colony East Delhi",
"Dilshad Garden East Delhi",
"Durgapuri Extension East Delhi",
"East Arjun Nagar East Delhi",
"East Nathu Colony East Delhi",
"East Old Seelampur East Delhi",
"East Ram Nagar East Delhi",
"F Block Laxmi Nagar East Delhi",
"GD Colony East Delhi",
"Gagan Vihar East Delhi",
"Gandhi Nagar East Delhi",
"Ganesh Nagar East Delhi",
"Ganesh Nagar 2 East Delhi",
"Ganga Vihar East Delhi",
"Gautam Puri East Delhi",
"Gautam Vihar East Delhi",
"Gazipur East Delhi",
"Geeta Colony East Delhi",
"Geeta Colony Block 8 East Delhi",
"Gharoli East Delhi",
"Gharoli Extension East Delhi",
"Ghazipur Dairy Farm East Delhi",
"Ghonda Patti East Delhi",
"Ghonda Patti Chauhan East Delhi",
"Gokalpur East Delhi",
"Gokalpur East East Delhi",
"Gokalpuri East Delhi",
"Gokul Puri East Delhi",
"Gopal Park East Delhi",
"Gorakh Park East Delhi",
"Govindpura East Delhi",
"Gujarat Vihar East Delhi",
"Guru Angad Nagar East Delhi",
"Hardev Puri East Delhi",
"Hargobind Enclave East Delhi",
"Harijan Basti East Delhi",
"Harsh Vihar East Delhi",
"IP Enclave East Delhi",
"Integrated Freight Complex East Delhi",
"Jagatpuri East Delhi",
"Jagatpuri Extension East Delhi",
"Jagriti Enclave East Delhi",
"Jawala Nagar East Delhi",
"Jheel Khurenja East Delhi",
"Jhilmil Colony East Delhi",
"Jitar Nagar East Delhi",
"Johripur East Delhi",
"Joshi Colony East Delhi",
"Jyoti Colony East Delhi",
"Jyoti Nagar East Delhi",
"Kabir Nagar East Delhi",
"Kabool Nagar East Delhi",
"Kailash Nagar East Delhi",
"Kalyan Puri East Delhi",
"Kanti Nagar East Delhi",
"Kanti Nagar Extension East Delhi",
"Karawal Nagar East Delhi",
"Kardam Puri East Delhi",
"Karkardooma East Delhi",
"Khajuri Khas East Delhi",
"Khichripur East Delhi",
"Kondli East Delhi",
"Krishan Kunj East Delhi",
"Krishan Kunj Extension Part 2 East Delhi",
"Krishna Nagar East Delhi",
"Krishna Nagar Extension East Delhi",
"Kundan Nagar East Delhi",
"Lalita Park East Delhi",
"Madhu Vihar East Delhi",
"Mandawali East Delhi",
"Mandoli East Delhi",
"Mandoli Extension East Delhi",
"Mangal Bazar East Delhi",
"Mansarovar Park East Delhi",
"Mayur Vihar East Delhi",
"Mayur Vihar 1 East Delhi",
"Mayur Vihar Phase 1 East Delhi",
"Mayur Vihar Phase 1 Extension East Delhi",
"Mayur Vihar Phase 2 East Delhi",
"Mohan Park East Delhi",
"Mustafabad East Delhi",
"Nand Nagri East Delhi",
"Nehru Vihar East Delhi",
"New Ashok Nagar East Delhi",
"New Kondli East Delhi",
"New Layal Pur East Delhi",
"New Layal Pur Colony East Delhi",
"New Seelampur East Delhi",
"New Usmanpur East Delhi",
"Nirman Vihar East Delhi",
"North Ghonda East Delhi",
"Old Seelampur East Delhi",
"Old Seemapuri East Delhi",
"Pandav Nagar East Delhi",
"Paryatan Vihar East Delhi",
"Priya Enclave East Delhi",
"Radhey Shyam Park East Delhi",
"Radhey Shyam Park Extension East Delhi",
"Radheypuri East Delhi",
"Raghubarpura East Delhi",
"Railway Colony East Delhi",
"Rajdhani Enclave East Delhi",
"Rajgarh Colony East Delhi",
"Ram Nagar East Delhi",
"Ram Vihar East Delhi",
"Ramesh Park East Delhi",
"Rani Garden East Delhi",
"Rishabh Vihar East Delhi",
"Rohitash Nagar East Delhi",
"Saboli East Delhi",
"Saboli Extention East Delhi",
"Saini Enclave East Delhi",
"Sakdarpur East Delhi",
"Saket Block East Delhi",
"Savita Vihar East Delhi",
"School Block East Delhi",
"Sector C Gharoli East Delhi",
"Seelampur East Delhi",
"Shahdara East Delhi",
"Shaheed Bhagat Singh Colony East Delhi",
"Shankar Vihar East Delhi",
"Shanti Vihar East Delhi",
"Shashi Garden East Delhi",
"Shastri Nagar East Delhi",
"Shastri Park East Delhi",
"Shiv Vihar East Delhi",
"Shivaji Park East Delhi",
"Shivpuri East Delhi",
"Shreshtha Vihar East Delhi",
"Shyam Enclave East Delhi",
"Silampur East Delhi",
"Subash Vihar East Delhi",
"Subhash Park East Delhi",
"Sunder Nagri East Delhi",
"Surajmal Vihar East Delhi",
"Surya Niketan East Delhi",
"Swasthya Vihar East Delhi",
"Taharpur Village East Delhi",
"Trilokpuri East Delhi",
"Tukhmirpur East Delhi",
"Una Enclave East Delhi",
"Usmanpur East Delhi",
"Vasundhara Enclave East Delhi",
"Vigyan Lok East Delhi",
"Vijay Park East Delhi",
"Vinod Nagar East Delhi",
"Vishwas Nagar East Delhi",
"Vivek Vihar East Delhi",
"Vivek Vihar Phase 1 East Delhi",
"Yojna Vihar East Delhi"
],
    "west-delhi": [
"A1 Block Paschim Vihar West Delhi",
"A2 Block Paschim Vihar West Delhi",
"A3 Block Paschim Vihar West Delhi",
"A4 Block Paschim Vihar West Delhi",
"A6 Block Paschim Vihar West Delhi",
"Adhyapak Nagar West Delhi",
"Agar Nagar West Delhi",
"Ajay Enclave West Delhi",
"Akash Vihar West Delhi",
"Aman Vihar West Delhi",
"Ambica Vihar West Delhi",
"Anand Parbat West Delhi",
"Anand Parbat Industrial Area West Delhi",
"Arihant Nagar West Delhi",
"Asha Park West Delhi",
"Ashok Nagar West Delhi",
"B2 Block Paschim Vihar West Delhi",
"B3 Block Paschim Vihar West Delhi",
"B4 Block Paschim Vihar West Delhi",
"Baba Farid Puri West Delhi",
"Bakkarwala West Delhi",
"Bali Nagar West Delhi",
"Baljeet Nagar West Delhi",
"Baprola West Delhi",
"Baprola Vihar West Delhi",
"Basai Darapur West Delhi",
"Bengali Colony West Delhi",
"Bhagwan Das Nagar West Delhi",
"Bhagwati Garden West Delhi",
"Bhagwati Garden Extension West Delhi",
"Bhera Enclave West Delhi",
"Block 11 West Patel Nagar West Delhi",
"Block 2A Nangloi Extension West Delhi",
"Block 31 West Patel Nagar West Delhi",
"Block 6 Ramesh Nagar West Delhi",
"Block 8 Subhash Nagar West Delhi",
"Block A West Delhi",
"Block A 1 Uttam Nagar West Delhi",
"Block A 2 Uttam Nagar West Delhi",
"Block A 3 Uttam Nagar West Delhi",
"Block A Kiran Garden West Delhi",
"Block A Panchvati Apartment West Delhi",
"Block B Patel Nagar West Delhi",
"Block B Rajouri Garden West Delhi",
"Block B Vijay Enclave West Delhi",
"Block BA Tagore Garden West Delhi",
"Block BC Mianwali Nagar West Delhi",
"Block C Mansa Ram Park West Delhi",
"Block D Janakpuri West Delhi",
"Block D Ram Datt Enclave West Delhi",
"Block D1 Uttam Nagar West Delhi",
"Block DG 1 Vikaspuri West Delhi",
"Block E Mangolpuri West Delhi",
"Block E Shyam Vihar Phase 1 West Delhi",
"Block F Hari Nagar West Delhi",
"Block F Rajouri Garden West Delhi",
"Block F Vikas Puri West Delhi",
"Block FA Mansarover Garden West Delhi",
"Block G Naraina Vihar West Delhi",
"Block G Uttam Nagar West Delhi",
"Block GH 14 Paschim Vihar West Delhi",
"Block GH 4 Meera Bagh West Delhi",
"Block GH 5 Meera Bagh West Delhi",
"Block H-3 Vikaspuri West Delhi",
"Block J Rajouri Garden West Delhi",
"Block J West Sagarpur West Delhi",
"Block JG 2 Vikaspuri West Delhi",
"Block L JJ Colony No 3 West Delhi",
"Block M Vikas Puri West Delhi",
"Block RZ Kali Nagar West Delhi",
"Block U Mangolpuri West Delhi",
"Block U Nihal Vihar West Delhi",
"Block Va Janakpuri West Delhi",
"Block X JJ Colony No 3 West Delhi",
"Block de Tagore Garden West Delhi",
"Bodella West Delhi",
"C Block Janakpuri West Delhi",
"C Block Vikaspuri West Delhi",
"Camp No 4 Jwalapuri West Delhi",
"Chanakya Place West Delhi",
"Chanakya Place 1 West Delhi",
"Chanchal Park West Delhi",
"Chand Nagar West Delhi",
"Chandan Vihar West Delhi",
"Chander Nagar West Delhi",
"Chaukhandi West Delhi",
"D Block Vikaspuri West Delhi",
"D Block West Patel Nagar West Delhi",
"DTC Colony Shadipur West Delhi",
"Dasghara West Delhi",
"Dashrath Puri West Delhi",
"Deenpur West Delhi",
"Deepak Vihar West Delhi",
"Dharampura West Delhi",
"Dichaon Kalan West Delhi",
"Dindarpur West Delhi",
"Durga Puri West Delhi",
"Dwarka Mor West Delhi",
"East Patel Nagar West Delhi",
"F Block Vikaspuri West Delhi",
"F Block Vishnu Garden West Delhi",
"F-2 Block Jai Vihar West Delhi",
"Fateh Nagar West Delhi",
"G Block Vikaspuri West Delhi",
"Gandhi Market West Delhi",
"Ganesh Nagar West Delhi",
"Ghevra West Delhi",
"Gopal Extension 2 West Delhi",
"Gopal Nagar West Delhi",
"Gopal Nagar Extension West Delhi",
"Gopal Nagar Extn 1 West Delhi",
"Guru Harkishan Nagar West Delhi",
"Guru Nanak Nagar West Delhi",
"Gurunanak Pura West Delhi",
"Hari Enclave West Delhi",
"Hari Nagar West Delhi",
"Harphool Vihar West Delhi",
"Hastsal West Delhi",
"Hind Nagar West Delhi",
"Inder Enclave West Delhi",
"Inderpuri West Delhi",
"Indira Park West Delhi",
"Indra Park West Delhi",
"J Block Vikaspuri West Delhi",
"JJ Colony West Delhi",
"JJ Colony Nangloi West Delhi",
"Jaffarpur Kalan West Delhi",
"Jai Vihar West Delhi",
"Jaidev Park West Delhi",
"Jain Colony West Delhi",
"Janakpuri West Delhi",
"Jharoda Kalan West Delhi",
"Kali Nagar West Delhi",
"Kamruddin Nagar West Delhi",
"Karampura West Delhi",
"Kashmiri Colony West Delhi",
"Khaira West Delhi",
"Khayala West Delhi",
"Khera Dabar West Delhi",
"Kiran Garden West Delhi",
"Kirari Extension West Delhi",
"Kirari Suleman Nagar West Delhi",
"Kirti Nagar West Delhi",
"Krishna Apartment West Delhi",
"Krishna Park Extension West Delhi",
"Krishna Puri West Delhi",
"Kunwar Singh Nagar West Delhi",
"L Block Hari Nagar West Delhi",
"Laxmi Vihar West Delhi",
"Lok Nayak Puram West Delhi",
"MBS Nagar West Delhi",
"Madanpur Dabas West Delhi",
"Madipur West Delhi",
"Mahaveer Nagar West Delhi",
"Mahavir Enclave West Delhi",
"Mahavir Enclave Part 1 West Delhi",
"Mahavir Enclave Part 2 West Delhi",
"Mahavir Enclave Part 3 West Delhi",
"Manak Vihar West Delhi",
"Manas Kunj West Delhi",
"Manglapuri West Delhi",
"Mangol Puri Industrial Area Phase 1 West Delhi",
"Mangolpur Khurd West Delhi",
"Mangolpuri West Delhi",
"Mangolpuri Industrial Area West Delhi",
"Mansa Ram Park West Delhi",
"Mansarovar Garden West Delhi",
"Masudabad West Delhi",
"Matiala West Delhi",
"Matiala Extension West Delhi",
"Mayapuri West Delhi",
"Mayapuri Industrial Area Phase 1 West Delhi",
"Mayapuri Industrial Area Phase 2 West Delhi",
"Meenakshi Garden West Delhi",
"Meera Bagh West Delhi",
"Mianwali Nagar West Delhi",
"Milk Scheme Colony West Delhi",
"Mirzapur West Delhi",
"Mohan Garden West Delhi",
"Moti Nagar West Delhi",
"Mubarakpur Dabas West Delhi",
"Mubarkpur West Delhi",
"Mukerjee Park West Delhi",
"Mukhram Park Extension West Delhi",
"Mundka West Delhi",
"Najafgarh West Delhi",
"Najafgarh Road West Delhi",
"Nanak Pura West Delhi",
"Nanda Block West Delhi",
"Nangal Raya West Delhi",
"Nangli Sakrawati West Delhi",
"Nangloi West Delhi",
"Nangloi Extension West Delhi",
"Nanhey Park West Delhi",
"Naraina West Delhi",
"Naraina Industrial Area Phase 1 West Delhi",
"Naraina Vihar West Delhi",
"Narang Colony West Delhi",
"Nawada West Delhi",
"Nawada Extension West Delhi",
"New Patel Nagar West Delhi",
"New Rohtak Road West Delhi",
"Nihal Vihar West Delhi",
"Nilothi West Delhi",
"Nilothi Extn West Delhi",
"Om Vihar West Delhi",
"Om Vihar Extension West Delhi",
"Om Vihar Phase 3 West Delhi",
"Palam Colony West Delhi",
"Palam Enclave West Delhi",
"Pankha Road West Delhi",
"Param Puri West Delhi",
"Paschim Puri West Delhi",
"Paschim Vihar West Delhi",
"Patel Nagar West Delhi",
"Peeragarhi West Delhi",
"Phase 1 Pocket B Mangolpuri Industrial Area West Delhi",
"Phase 4 Om Vihar West Delhi",
"Phase 5 Om Vihar West Delhi",
"Pratap Enclave West Delhi",
"Pratap Vihar West Delhi",
"Prem Nagar West Delhi",
"Prem Nagar 3 West Delhi",
"Press Colony West Delhi",
"Punjabi Bagh West Delhi",
"Punjabi Bagh Extension West Delhi",
"Punjabi Basti West Delhi",
"Raghubir Nagar West Delhi",
"Raja Garden West Delhi",
"Rajapuri West Delhi",
"Rajasthan Colony West Delhi",
"Rajouri Garden West Delhi",
"Ram Datt Enclave West Delhi",
"Ram Park West Delhi",
"Rama Park West Delhi",
"Ramchander Enclave West Delhi",
"Ranaji Enclave West Delhi",
"Ranhola West Delhi",
"Ranhola Extension West Delhi",
"Rani Bagh West Delhi",
"Ranjeet Nagar West Delhi",
"Ratan Park West Delhi",
"Rawta More West Delhi",
"Razapur Khurd West Delhi",
"Reserve Bank Enclave West Delhi",
"Roshanpura West Delhi",
"Sagarpur West Delhi",
"Sainik Enclave West Delhi",
"Sainik Nagar West Delhi",
"Sainik Vihar West Delhi",
"Saraswati Garden West Delhi",
"Shahpura West Delhi",
"Shiv Nagar West Delhi",
"Shiv Ram Park Extention 2 West Delhi",
"Shiv Vihar West Delhi",
"Shyam Nagar West Delhi",
"Shyam Vihar West Delhi",
"Shyam Vihar 1 West Delhi",
"Shyam Vihar Phase 1 West Delhi",
"Sitapuri West Delhi",
"South Patel Nagar West Delhi",
"Subhash Park West Delhi",
"Sultanpur Majra Village West Delhi",
"Sultanpuri West Delhi",
"T Extension West Delhi",
"Tagore Garden West Delhi",
"Tihar Village West Delhi",
"Tikri Kalan West Delhi",
"Tilak Nagar West Delhi",
"Tilangpur Kotla West Delhi",
"Todapur West Delhi",
"Tyagi Vihar West Delhi",
"Udyog Nagar West Delhi",
"Uttam Nagar West Delhi",
"Vaishali Colony West Delhi",
"Vani Vihar West Delhi",
"Vashist Park West Delhi",
"Vijay Enclave West Delhi",
"Vijay Vihar West Delhi",
"Vikas Nagar West Delhi",
"Vikas Puri West Delhi",
"Vikas Vihar West Delhi",
"Vikaspuri West Delhi",
"Vikrant Enclave West Delhi",
"Vipin Garden West Delhi",
"Vipin Garden Extension West Delhi",
"Vipin Garden Extension North Block West Delhi",
"Vishnu Garden West Delhi",
"Vishwas Park West Delhi",
"Ware Housing Scheme West Delhi",
"West Patel Nagar West Delhi",
"Zaildar Enclave West Delhi"
],
  };

  const createSlug = (name) =>
    name.toLowerCase().replace(/\s+/g, "-");

  const locations = zones[zone] || [];

  const formattedZone = zone
    ?.replace(/-/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());

useEffect(() => {
  const checkScreen = () => {
    setIsMobile(window.innerWidth < 640);
  };

  checkScreen();
  window.addEventListener("resize", checkScreen);

  return () => window.removeEventListener("resize", checkScreen);
}, []);
  return (
   <section className="min-h-screen bg-white py-16">
  <div className="max-w-7xl mx-auto px-6">
   <div className="py-5">
    <Breadcrumb/>
   </div>
    {/* HEADER */}
    <div className=" mb-12">

      <h1 className="text-2xl md:text-4xl font-bold text-red-600 mb-4">
        Real Estate in {formattedZone}
      </h1>

      <p className="text-gray-600 max-w-2xl">
        Browse verified property dealers across {formattedZone}.
      </p>

    </div>

    {/* LIST */}
    <ul className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-y-1 gap-x-8 text-gray-700">

      {(isMobile && !showAll
  ? locations.slice(0, 20)
  : locations
).map((location, index) => (
        <li key={index}>
  <Link
href={`/delhi/property-dealer-in-${createSlug(location)}`}
    className="transition font-medium hover:text-red-600 hover:font-bold hover:underline"
  >
    Property Dealer in {location}
  </Link>
</li>
      ))}

    </ul>
{isMobile && !showAll && locations.length > 20 && (
  <div className="mt-6 text-center">
    <span
      onClick={() => setShowAll(true)}
      className="cursor-pointer text-red-600 font-medium hover:underline"
    >
      Know More
    </span>
  </div>
)}

  </div>
</section>


  );
}
