import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Script from "next/script"; // ✅ AdSense ke liye


// --------------------------

import { DealerProvider } from "@/context/propertydealercontext/DealerContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       
        <DealerProvider>

      

          {children}

          

        </DealerProvider>
      </body>
    </html>
  );
}
