import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Script from "next/script"; // ✅ AdSense ke liye


// --------------------------

import { DealerProvider } from "@/context/propertydealercontext/DealerContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      {/* ✅ AdSense Script Added (Head) */}
      <head>
        <Script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-XXXXXXXXXXXXXXXX"
          crossOrigin="anonymous"
          strategy="afterInteractive"
        />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 🔥 CONTEXT WRAP */}
        <DealerProvider>

          {/* OPTIONAL Navbar (agar layout me use karte ho) */}
      

          {children}

          

        </DealerProvider>
      </body>
    </html>
  );
}
