export const DOMAIN_LAYOUT_MAP = {
  "propertydeler-gold-frontend-9wvp.vercel.app": "faridabad",
  "propertydeler-gold-frontend.vercel.app": "gurgaon",
  "propertydeler-gold-frontend-lp3d.vercel.app": "hisar",
  "propertydeler-gold-frontend-xkw9.vercel.app": "noida",
  "propertydeler-gold-frontend-k2da.vercel.app": "delhi",
  "propertydeler-gold-frontend-w423.vercel.app": "sonipat",
  "https://propertydealerinhisar.com":"hisar",
  "www.propertydealerinhisar.com":"hisar",
  "www.propertydealerinhisar.com/":"hisar",
  "propertydealerinfaridabad.com":"faridabad",
  "www.propertydealerinfaridabad.com":"faridabad",
  "propertydealerinnoida.com":"noida",
  "www.propertydealerinnoida.com":"noida",
  "propertydealeringurgaon.com":"gurgaon",
  "www.propertydealeringurgaon.com":"gurgaon",
  "propertydealerindelhi.com":"delhi",
  "www.propertydealerindelhi.com":"delhi",
  "propertyforsalenearme.in":"haryana",
  "www.propertyforsalenearme.in":"haryana",
    "projectwallah.live":"hisar",
    "www.projectwallah.live":"hisar",
    "https://www.projectwallah.live":"hisar",
    "https://projectwallah.live":"hisar",
    "https://www.projectwallah.live/":"hisar",
    "https://projectwallah.live/":"hisar",
  "property-dealer-in-hisar-2.vercel.app": "hisar",
"localhost:3000": "gurgaon",
};

export const DEFAULT_LAYOUT = "sonipat"
